; This file provides the utilities required to load/save a game.
(in-package #:latrunculi)

(defun save-game (filename board turn player0 player1)
  (let ((out (open-output-file filename))) 
    (write board out)
    (write turn out)
    (write player0 out)
    (write player1 out) 
    (close-output-port out)
    )
  )

(defun load-game (filename)
  (let* ((in (open-input-file filename)) 
         (board (read in))
         (turn (read in))
         (player0 (read in))
         (player1 (read in))
         ) 
    (close-input-port in) 
    (values board turn player0 player1)
    )
  )
